language: haxe
sudo: false
dist: trusty
haxe:
 - development

install:
 - haxelib git vshaxe-build https://github.com/vshaxe/vshaxe-build
 - haxelib git haxeserver https://github.com/simn/haxeserver

script:
 - haxelib run vshaxe-build -t language-server -t language-server-tests -m both